plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  
title: Code Crumbs
author: Tomasz Orszulak
description: Blog site for programming knowledge sharing (c#, js, sql)

url: https://torszulak.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
paginate: 5

social:
    github: torszulak
    linkedin: tomasz-orszulak

# google_analytics: ""

# disqus:
#    shortname: torszulak